homepage:
  path: /
  controller: DefaultController::homeAction
  methods: [GET,POST]

notFound:
  path: /404/
  controller: NotFoundController::notFound
  methods: [GET,POST]

blog:
  path: /blog/
  controller: BlogController::blog
  methods: [GET,POST]

portfolio:
  path: /portfolio/
  controller: PortFolioController::portFolio
  methods: [GET,POST]

contact:
  path: /contact/
  controller: ContactController::contact
  methods: [GET,POST]

registration:
  path: /registration/
  controller: RegistController::registAction
  methods: [GET,POST]

resume:
  path: /resume/
  controller: ResumeController::resume
  methods: [GET,POST]
  requirements:

profil:
  path: /profil/
  controller: ProfilController::profil
  methods: [GET,POST]
  requirements:

connect:
  path: /connection/
  controller: ConnectController::connect
  methods: [GET,POST]
  requirements: